modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="COFH Don't Be A Jerk"
[[mods]] #mandatory
modId="cinematic_transitions" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Cinematic Transitions" #mandatory
updateJSONURL="" #optional
authors="winterSteve25" #optional
description='''
'''
[[dependencies.cinematic_transitions]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="[36,)" #mandatory
   ordering="NONE"
   side="BOTH"
[[dependencies.cinematic_transitions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"